version: '3'
services:
  api:
    container_name: flask-api
    build:
      context: .
      target: debug
    ports:
      - 5678:5678
      - 5000:5000
    volumes:
      - .:/dev-colab-api
    environment:
      - FLASK_DEBUG=1
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]